# Generated by Django 3.1.7 on 2021-05-20 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingPatients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issue', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_next', models.BooleanField(default=False)),
                ('in_session', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('person_present', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docAppoint.waitingpatients')),
            ],
        ),
    ]
