# Generated by Django 3.1.7 on 2021-05-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docAppoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsession',
            name='person_present',
            field=models.CharField(max_length=255),
        ),
    ]
