# Generated by Django 3.1.7 on 2021-05-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docAppoint', '0002_auto_20210520_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('issue', models.TextField()),
                ('time_served', models.DateTimeField()),
            ],
        ),
    ]
