# Generated by Django 3.1.7 on 2021-05-20 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docAppoint', '0003_patients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patients',
            options={'ordering': ['-time_served'], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
    ]
