# Generated by Django 3.1.7 on 2021-05-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docAppoint', '0004_auto_20210520_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitingpatients',
            name='issue',
            field=models.TextField(),
        ),
    ]
